spring:
  application:
    name: hotSearchWeb
  server:
    port: 8080
    servlet:
      context-path: /hot
  data:
    redis:
    host: localhost
    port: 6379
    password: 123456
    connect-timeout: 3000

